name: Snapshot Build
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-lates
    strategy:
      matrix: { project: ['dashboard', 'runner'] }
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Get Short Hash
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Authenticate with Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Publish Image
        uses: docker/build-push-action@v2
        with:
          context: ${{ project }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}-${{ matrix.project }}:${SHORT_SHA}
          push: false
