name: Release Build
on: 
  release:
    types: [created]
  jobs:
    build:
      name: Build and Publish Docker Image
      runs-on: ubuntu-latest
      strategy:
        matrix: { project: ['dashboard', 'runner'] }
      steps:
        - name: Clone Repository
          uses: actions/checkout@v3
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Authenticate with Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Build and Publish Image
          uses: docker/build-push-action@v2
          with:
            context: ${{ matrix.project }}
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/candor-${{ matrix.project }}:${{ github.event.release.tag_name }}
              ${{ secrets.DOCKERHUB_USERNAME }}/candor-${{ matrix.project }}:latest
            build-args: |
              CANDOR_BUILD_VERSION=${{ github.event.release.tag_name }}
            push: true