name: Code Quality
on: [push]
jobs:
  cq:
    name: Run Lint and Tests
    runs-on: ubuntu-latest
    strategy:
      matrix: { project: ['dashboard/frontend', 'dashboard/backend', 'runner'] }
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Clean Install
        run: npm ci
        working-directory: ${{ matrix.project }}
      - name: Lint
        run: npm run lint:nofix
        working-directory: ${{ matrix.project }}
      - name: Test
        run: npm run test
        working-directory: ${{ matrix.project }}